### ISSUE TITLE
NullPointer Exception with modded alien race

### ISSUE THREAD

**Issue by sdp0et** [FluffierThanThou/RelationsTab#17] opened 2017-04-11 00:00 UTC
This may not be a bug report as much as a request for help narrowing down an incompatibility.

My symptoms seem very similar to closed issue: [Error with Relations Tab [HardcoreSK] #8](https://github.com/FluffierThanThou/RelationsTab/issues/8)

I created a new colony last week with the only new mods being Humanoid Aliens and Elder Things.  When I look at the factions graph I see something similar to the screenshot as in the linked issue.  However, the there is only one faction of the alien race and it's leader draws fine.  I can't tell exactly which factions are no drawn, but mine (normal human) is one that is not.  I can select any of the human factions and the graph updates but I cannot select the missing factions or the alien one.

I've started a new save with these mods enabled and have the same effect (alien draws fine, several other factions do not. One created without either of those mods does not have the issue.

I've asked that mod creator if there is anything changed about faction relations but I wanted to see if you had any ideas to narrow things down since you are familiar with what RelationsTab is trying to do.

Here's the stacktrace and a screenshot:

Exception filling window for Fluffy_Relations.MainTabWindow_Relations: System.NullReferenceException: Object reference not set to an instance of an object
  at Fluffy_Relations.PawnSlotDrawer.DrawPawnInSlot (Verse.Pawn pawn, Rect slot) [0x00000] in <filename unknown>:0 
  at Fluffy_Relations.PawnSlotDrawer.DrawSlot (Verse.Pawn pawn, Rect slot, Boolean drawBG, Boolean drawLabel, Boolean drawLabelBG, Boolean drawHealthBar, Boolean drawStatusIcons, System.String label) [0x00000] in <filename unknown>:0 
  at Fluffy_Relations.ForceDirectedGraph.FactionNode.Draw () [0x00000] in <filename unknown>:0 
  at Fluffy_Relations.ForceDirectedGraph.Graph.Draw (Rect canvas) [0x00000] in <filename unknown>:0 
  at Fluffy_Relations.MainTabWindow_Relations.DrawFactionRelations () [0x00000] in <filename unknown>:0 
  at Fluffy_Relations.MainTabWindow_Relations.DoWindowContents (Rect canvas) [0x00000] in <filename unknown>:0 
  at HugsLib.GuiInject.WindowDetour+<>c__DisplayClass1.<_WindowOnGUI>b__0 (Int32 x) [0x00000] in <filename unknown>:0 
Verse.Log:Error(String)
HugsLib.GuiInject.<>c__DisplayClass1:<_WindowOnGUI>b__0(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, GUISkin, Int32, Single, Single, GUIStyle)

![elder things relations](https://cloud.githubusercontent.com/assets/5922308/24887239/f3c310b2-1e1f-11e7-9cda-bfcb8d61ce39.jpg)

**Comment by FluffierThanThou** [comment] 2017-05-12 22:34
probably duplicate of #16

**Closed as completed by FluffierThanThou** 2017-05-12 22:34 UTC
